language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: Tests
      script:
        - npm test
        #- npx semantic-release --dry-run --generate-notes

    - stage: release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
